version: "2.1"

services:
  database:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - ./docker/:/etc/mysql/conf.d
      - ./docker/database-storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
